--[[
    init.lua
    Created: 08/09/2026 16:40:41
    Description: Autogenerated script file for the map chapter_card.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local chapter_card = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chapter_card.Init(map)
--Engine callback function
function chapter_card.Init(map)


end

---chapter_card.Enter(map)
--Engine callback function
function chapter_card.Enter(map)
  GAME:GroundSave()

  GAME:CutsceneMode(true)
  GROUND:Hide("PLAYER")
  GAME:FadeIn(60)

  local coro1 = TASK:BranchCoroutine(function() UI:WaitShowTitle(STRINGS:Format(STRINGS.MapStrings['ChapterTitle_'..tostring(SV.Progression.Chapter)]), 60)
												  GAME:WaitFrames(300)
												  UI:WaitHideTitle(60) end)
  local coro2 = TASK:BranchCoroutine(function() UI:WaitShowBG("ChapterCard_"..tostring(SV.Progression.Chapter), 1, 60)
												  GAME:WaitFrames(300)
												  UI:WaitHideBG(60) end)
  TASK:JoinCoroutines({coro1})

  GAME:WaitFrames(60)

  if (SV.Progression.Chapter == 1) then
    GAME:EnterGroundMap("chp1_ultra", "Entrance")
  else

  end
end

---chapter_card.Exit(map)
--Engine callback function
function chapter_card.Exit(map)


end

---chapter_card.Update(map)
--Engine callback function
function chapter_card.Update(map)


end

---chapter_card.GameSave(map)
--Engine callback function
function chapter_card.GameSave(map)


end

---chapter_card.GameLoad(map)
--Engine callback function
function chapter_card.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chapter_card

