--[[
    init.lua
    Created: 07/24/2026 17:03:00
    Description: Autogenerated script file for the map jny_cutscenes.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local jny_cutscenes = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---jny_cutscenes.Init(zone)
--Engine callback function
function jny_cutscenes.Init(zone)


end

---jny_cutscenes.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function jny_cutscenes.EnterSegment(zone, rescuing, segmentID, mapID)


end

---jny_cutscenes.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function jny_cutscenes.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---jny_cutscenes.Rescued(zone, name, mail)
--Engine callback function
function jny_cutscenes.Rescued(zone, name, mail)


end

return jny_cutscenes

