--[[
    init.lua
    Created: 06/28/2026 17:06:56
    Description: Autogenerated script file for the map start_camp.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local start_camp = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---start_camp.Init(zone)
--Engine callback function
function start_camp.Init(zone)


end

---start_camp.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function start_camp.EnterSegment(zone, rescuing, segmentID, mapID)


end

---start_camp.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function start_camp.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---start_camp.Rescued(zone, name, mail)
--Engine callback function
function start_camp.Rescued(zone, name, mail)


end

return start_camp

