--[[
    init.lua
    Created: 08/10/2026 21:19:33
    Description: Autogenerated script file for the map chp1_solgaleo.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'jnw.common'

-- Package name
local chp1_solgaleo = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chp1_solgaleo.Init(map)
--Engine callback function
function chp1_solgaleo.Init(map)


end

---chp1_solgaleo.Enter(map)
--Engine callback function
function chp1_solgaleo.Enter(map)

  GROUND:Hide("PLAYER")
  GAME:FadeIn(20)
  COMMON.SetSpeakerUnknown(nil)

  local dialogues = {
    STRINGS:Format(STRINGS.MapStrings['Dialogue_1']),
    STRINGS:Format(STRINGS.MapStrings['Dialogue_2']),
    STRINGS:Format(STRINGS.MapStrings['Dialogue_3']),
  }

  for i = 1, 2 do
    UI:WaitShowDialogue(dialogues[i])
    GAME:WaitFrames(60)
  end
  GAME:WaitFrames(60)

  UI:WaitShowBG("Solgaleo", 60, 60)
  GAME:WaitFrames(60)
  UI:WaitShowDialogue(dialogues[3])
  GAME:WaitFrames(120)
  UI:WaitHideBG(60)
end

---chp1_solgaleo.Exit(map)
--Engine callback function
function chp1_solgaleo.Exit(map)


end

---chp1_solgaleo.Update(map)
--Engine callback function
function chp1_solgaleo.Update(map)


end

---chp1_solgaleo.GameSave(map)
--Engine callback function
function chp1_solgaleo.GameSave(map)


end

---chp1_solgaleo.GameLoad(map)
--Engine callback function
function chp1_solgaleo.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chp1_solgaleo

