--[[
    init.lua
    Created: 06/28/2026 20:35:46
    Description: Autogenerated script file for the map island_camp.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local island_camp = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---island_camp.Init(zone)
--Engine callback function
function island_camp.Init(zone)


end

---island_camp.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function island_camp.EnterSegment(zone, rescuing, segmentID, mapID)


end

---island_camp.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function island_camp.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---island_camp.Rescued(zone, name, mail)
--Engine callback function
function island_camp.Rescued(zone, name, mail)


end

return island_camp

