--[[
    init.lua
    Created: 07/24/2026 17:01:11
    Description: Autogenerated script file for the map start_quiz.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'jnw.common'

-- Package name
local start_quiz = {}

-- 

-------------------------------
-- Map Callbacks
-------------------------------
---start_quiz.Init(map)
--Engine callback function
function start_quiz.Init(map)


end

local starterListMale = {
-- Gen 1
	RogueEssence.Dungeon.MonsterID("bulbasaur", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("charmander", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("squirtle", 0, "normal", Gender.Male),
	
	RogueEssence.Dungeon.MonsterID("cubone", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("pikachu", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("vulpix", 0, "normal", Gender.Male),
  	RogueEssence.Dungeon.MonsterID("vulpix", 1, "normal", Gender.Male),

--Gen 2
	RogueEssence.Dungeon.MonsterID("chikorita", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("cyndaquil", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("totodile", 0, "normal", Gender.Male),

	RogueEssence.Dungeon.MonsterID("phanpy", 0, "normal", Gender.Male),

--Gen 3
	RogueEssence.Dungeon.MonsterID("treecko", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("torchic", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("mudkip", 0, "normal", Gender.Male),
	
	RogueEssence.Dungeon.MonsterID("skitty", 0, "normal", Gender.Male),
--Gen 4
	RogueEssence.Dungeon.MonsterID("turtwig", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("chimchar", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("piplup", 0, "normal", Gender.Male),
	
  	RogueEssence.Dungeon.MonsterID("buneary", 0, "normal", Gender.Male),
  	RogueEssence.Dungeon.MonsterID("buizel", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("shinx", 0, "normal", Gender.Male),
--Gen 5
	RogueEssence.Dungeon.MonsterID("snivy", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("tepig", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("oshawott", 0, "normal", Gender.Male),
	
  	RogueEssence.Dungeon.MonsterID("minccino", 0, "normal", Gender.Male),
  	RogueEssence.Dungeon.MonsterID("deerling", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("axew", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("zorua", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("zorua", 1, "normal", Gender.Male),

--Gen 6	
  	RogueEssence.Dungeon.MonsterID("chespin", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("fennekin", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("froakie", 0, "normal", Gender.Male),
	
  	RogueEssence.Dungeon.MonsterID("espurr", 0, "normal", Gender.Male),
  	RogueEssence.Dungeon.MonsterID("helioptile", 0, "normal", Gender.Male),
  	RogueEssence.Dungeon.MonsterID("noibat", 0, "normal", Gender.Male),

--Gen 7	
	RogueEssence.Dungeon.MonsterID("rowlet", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("litten", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("popplio", 0, "normal", Gender.Male),

  	RogueEssence.Dungeon.MonsterID("rockruff", 0, "normal", Gender.Male),
  
--Gen 8	
	RogueEssence.Dungeon.MonsterID("grookey", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("scorbunny", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("sobble", 0, "normal", Gender.Male),

--Gen 9	
	RogueEssence.Dungeon.MonsterID("sprigatito", 0, "normal", Gender.Male),	 
	RogueEssence.Dungeon.MonsterID("fuecoco", 0, "normal", Gender.Male),
	RogueEssence.Dungeon.MonsterID("quaxly", 0, "normal", Gender.Male),	

  	RogueEssence.Dungeon.MonsterID("pawmi", 0, "normal", Gender.Male)
}

local starterListFemale = {
-- Gen 1
	RogueEssence.Dungeon.MonsterID("bulbasaur", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("charmander", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("squirtle", 0, "normal", Gender.Female),
	
	RogueEssence.Dungeon.MonsterID("cubone", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("pikachu", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("vulpix", 0, "normal", Gender.Female),
  	RogueEssence.Dungeon.MonsterID("vulpix", 1, "normal", Gender.Female),

--Gen 2
	RogueEssence.Dungeon.MonsterID("chikorita", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("cyndaquil", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("totodile", 0, "normal", Gender.Female),

	RogueEssence.Dungeon.MonsterID("phanpy", 0, "normal", Gender.Female),

--Gen 3
	RogueEssence.Dungeon.MonsterID("treecko", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("torchic", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("mudkip", 0, "normal", Gender.Female),

	RogueEssence.Dungeon.MonsterID("skitty", 0, "normal", Gender.Female),
--Gen 4
	RogueEssence.Dungeon.MonsterID("turtwig", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("chimchar", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("piplup", 0, "normal", Gender.Female),

  	RogueEssence.Dungeon.MonsterID("buneary", 0, "normal", Gender.Female),
  	RogueEssence.Dungeon.MonsterID("buizel", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("shinx", 0, "normal", Gender.Female),
--Gen 5
	RogueEssence.Dungeon.MonsterID("snivy", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("tepig", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("oshawott", 0, "normal", Gender.Female),

  	RogueEssence.Dungeon.MonsterID("minccino", 0, "normal", Gender.Female),
  	RogueEssence.Dungeon.MonsterID("deerling", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("axew", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("zorua", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("zorua", 1, "normal", Gender.Female),

--Gen 6	
  	RogueEssence.Dungeon.MonsterID("chespin", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("fennekin", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("froakie", 0, "normal", Gender.Female),
	
  	RogueEssence.Dungeon.MonsterID("espurr", 0, "normal", Gender.Female),
  	RogueEssence.Dungeon.MonsterID("helioptile", 0, "normal", Gender.Female),
  	RogueEssence.Dungeon.MonsterID("noibat", 0, "normal", Gender.Female),

--Gen 7	
	RogueEssence.Dungeon.MonsterID("rowlet", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("litten", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("popplio", 0, "normal", Gender.Female),

  	RogueEssence.Dungeon.MonsterID("rockruff", 0, "normal", Gender.Female),
  
--Gen 8	
	RogueEssence.Dungeon.MonsterID("grookey", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("scorbunny", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("sobble", 0, "normal", Gender.Female),

--Gen 9	
	RogueEssence.Dungeon.MonsterID("sprigatito", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("fuecoco", 0, "normal", Gender.Female),
	RogueEssence.Dungeon.MonsterID("quaxly", 0, "normal", Gender.Female),	

  	RogueEssence.Dungeon.MonsterID("pawmi", 0, "normal", Gender.Female)
}

local starterList = {
-- Gen 1
	RogueEssence.Dungeon.MonsterID("bulbasaur", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("squirtle", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("charmander", 0, "normal", Gender.Genderless),
	
	RogueEssence.Dungeon.MonsterID("cubone", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("pikachu", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("vulpix", 0, "normal", Gender.Genderless),
  	RogueEssence.Dungeon.MonsterID("vulpix", 1, "normal", Gender.Genderless),

--Gen 2
	RogueEssence.Dungeon.MonsterID("chikorita", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("totodile", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("cyndaquil", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("phanpy", 0, "normal", Gender.Genderless),

--Gen 3
	RogueEssence.Dungeon.MonsterID("treecko", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("mudkip", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("torchic", 0, "normal", Gender.Genderless),
	
	RogueEssence.Dungeon.MonsterID("skitty", 0, "normal", Gender.Genderless),
--Gen 4
	RogueEssence.Dungeon.MonsterID("turtwig", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("piplup", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("chimchar", 0, "normal", Gender.Genderless),
	
  RogueEssence.Dungeon.MonsterID("buneary", 0, "normal", Gender.Genderless),
  RogueEssence.Dungeon.MonsterID("buizel", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("shinx", 0, "normal", Gender.Genderless),
--Gen 5
	RogueEssence.Dungeon.MonsterID("snivy", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("oshawott", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("tepig", 0, "normal", Gender.Genderless),
	
  RogueEssence.Dungeon.MonsterID("minccino", 0, "normal", Gender.Genderless),
  RogueEssence.Dungeon.MonsterID("deerling", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("axew", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("zorua", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("zorua", 1, "normal", Gender.Genderless),

--Gen 6	
  RogueEssence.Dungeon.MonsterID("chespin", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("froakie", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("fennekin", 0, "normal", Gender.Genderless),
	
  RogueEssence.Dungeon.MonsterID("espurr", 0, "normal", Gender.Genderless),
  RogueEssence.Dungeon.MonsterID("helioptile", 0, "normal", Gender.Genderless),
  RogueEssence.Dungeon.MonsterID("noibat", 0, "normal", Gender.Genderless),

--Gen 7	
	RogueEssence.Dungeon.MonsterID("rowlet", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("popplio", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("litten", 0, "normal", Gender.Genderless),

  RogueEssence.Dungeon.MonsterID("rockruff", 0, "normal", Gender.Genderless),
  
--Gen 8	
	RogueEssence.Dungeon.MonsterID("grookey", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("sobble", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("scorbunny", 0, "normal", Gender.Genderless),

--Gen 9	
	RogueEssence.Dungeon.MonsterID("sprigatito", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("quaxly", 0, "normal", Gender.Genderless),		 
	RogueEssence.Dungeon.MonsterID("fuecoco", 0, "normal", Gender.Genderless),

  RogueEssence.Dungeon.MonsterID("pawmi", 0, "normal", Gender.Genderless)
}

local egg_move_list = {
		--vanilla egg moves
		["bulbasaur"] = "ingrain",
		["charmander"] = "metal_claw",
		["squirtle"] = "fake_out",
		["pikachu"] = "charge",
		["eevee"] = "wish",
		["cubone"] = "ancient_power",
		["meowth"] = "covet",
		["vulpix"] = "disarming_voice", 
		["eevee"] = "wish",
		["chikorita"] = "heal_pulse",
		["cyndaquil"] = "ancient_power",
		["totodile"] = "aqua_jet",
		["phanpy"] = "endeavor",
		["treecko"] = "grass_whistle",
		["torchic"] = "counter",
		["mudkip"] = "wide_guard",
		["skitty"] = "zen_headbutt",
		["shinx"] = "quick_attack",
		["buizel"] = "aqua_ring",
		["riolu"] = "bullet_punch",
		--origins egg moves
		["buneary"] = "fake_out",
		["zorua"] = "sucker_punch",
		["axew"] = "aqua_tail",
		["zorua"] = "extrasensory"
	}

---start_quiz.Enter(map)
--Engine callback function
function start_quiz.Enter(map)

  -- 启动
  UI:WaitShowBG("Black", 1, 1)
  GROUND:Hide("PLAYER")
  UI:ResetSpeaker()
  UI:SetCenter(true)
  GAME:FadeIn(20)

  -- 介绍
  GAME:WaitFrames(120)
  for i = 1, 4, 1 do
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['Intro_'..tostring(i)]), -1)
  end
  GAME:WaitFrames(20)
  SOUND:PlayBGM("003 - Welcome to the World of Pokémon!.ogg", true)
  UI:WaitHideBG(60)
  
  UI:SetCenter(false)

  -- 滑稽一下
	-- UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Quiz_Skip']), true)
  --   UI:WaitForChoice()
	-- skipQuiz = UI:ChoiceResult()
  -- if skipQuiz == true then
  --   UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Skip_Yes']))
  --   GAME:WaitFrames(120)
  -- end
  -- 
  UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Quiz_MysteryDungeon']))
  UI:WaitForChoice()
  result = UI:ChoiceResult()
  SV.General.PlayedMysteryDungeon = result

  choices = {STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_1']),
           STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_2'])}

  UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_Choice']), choices, 1, -1)
  UI:WaitForChoice()
  result = UI:ChoiceResult()
  gender = result

  local continue = false
  local txt = STRINGS:Format(STRINGS.MapStrings['Starter_Select'])
  pkm = -1

  local heroListNum = 0
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Select_Starter']))

while not continue do
	if gender == 1 then
		UI:ChooseMonsterMenu(txt, starterListMale)
	elseif gender == 2 then
		UI:ChooseMonsterMenu(txt, starterListFemale)
	end	
	UI:WaitForChoice()	
	local result = UI:ChoiceResult()
	pkm = result
	
	for i = 1, #starterList do
		if starterList[i] == pkm then
			heroListNum = i
			break
		end
	end
	
	GAME:RemovePlayerTeam(0)
	GAME:WaitFrames(1)
	_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))
	
	--add egg move
	if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(0), 3) ~= "" then 
		GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species], 3) -- override move in slot 4 if 4 moves are known
	else 
		GAME:LearnSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species])
	end
	
	COMMON.SetPlayerFromData(pkm)
	UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'], _DATA:GetMonster(pkm.Species):GetColoredName()))
	UI:WaitForChoice()
	continue = UI:ChoiceResult()
	if not continue then
		GROUND:Hide("PLAYER")
	end
end
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings["Quiz_Starter_Name"]))

-- Starter Name
local ch = false
local name = ""
while not ch do
    name = ""
	while name == "" do
      UI:NameMenu(STRINGS:Format(STRINGS.MapStrings['Starter_Name']), "")
      UI:WaitForChoice()
      name = UI:ChoiceResult()
	end
	
	GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(0), name)
    UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Name_Confirm'], name), true)
    UI:WaitForChoice()
    ch = UI:ChoiceResult()
end

GROUND:Hide("PLAYER")

-- 搭档设置

GAME:MoveCamera(48, 0, 1, true)

_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, RogueEssence.Dungeon.MonsterID("missingno", 0, "normal", Gender.Genderless), 5, "", 0))
UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Partner_Intro']))

local continue = false
local txt = STRINGS:Format(STRINGS.MapStrings['Partner_Select'])
pkm = -1

local partnerListNum = 0
local partner_ground = nil
while not continue do
	UI:ChooseMonsterMenu(txt, starterList)
	UI:WaitForChoice()	
	local result = UI:ChoiceResult()
	print(result)
	pkm = result
	
	for i = 1, #starterList do
		if starterList[i] == pkm then
			partnerListNum = i
			break
		end
	end
	
	GAME:RemovePlayerTeam(1)
	GAME:WaitFrames(1)
	_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))
	local member = _DATA.Save.ActiveTeam.Players[1]
	GROUND:SpawnerSetSpawn("PARTNER", member)
	partner_ground = GROUND:SpawnerDoSpawn("PARTNER")
	local partnerName = partner_ground.EntName
	
	UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'], _DATA:GetMonster(pkm.Species):GetColoredName()))
	UI:WaitForChoice()
	continue = UI:ChoiceResult()
	if _DATA.Save.ActiveTeam.Players[0].Element1 == _DATA.Save.ActiveTeam.Players[1].Element1 and continue then
		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Partner_Warning'], _DATA:GetMonster(pkm.Species):GetColoredName()))
		UI:WaitForChoice()
		continue = UI:ChoiceResult()
	end
	if not continue then
		GROUND:RemoveCharacter(partnerName)
		GAME:RemovePlayerTeam(1)
	end

end

--Partner Gender
choices = {STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_1']),
           STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_2'])}

UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Partner_Gender']), choices, 1, -1)
UI:WaitForChoice()
result = UI:ChoiceResult()
GAME:RemovePlayerTeam(1)

GAME:WaitFrames(1)

if result == 1 then pkm.Gender = Gender.Male end
if result == 2 then pkm.Gender = Gender.Female end

choices = {STRINGS:Format(STRINGS.MapStrings['Partner_TalkKind_Docile']),
           STRINGS:Format(STRINGS.MapStrings['Partner_TalkKind_Calm'])}
UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Partner_TalkKind']), choices, 1, -1)
UI:WaitForChoice()
result = UI:ChoiceResult()
SV.Personality.PartnerTalkKind = result

GAME:RemovePlayerTeam(1)
GAME:WaitFrames(1)
_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))

--add egg move (thanks again palika)
if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(1), 3) ~= "" then 
	GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(1), egg_move_list[pkm.Species], 3) -- override move in slot 4 if 4 moves are known
else 
	GAME:LearnSkill(GAME:GetPlayerPartyMember(1), egg_move_list[pkm.Species])
end

_DATA.Save.ActiveTeam.Players[1].IsFounder = true
_DATA.Save.ActiveTeam.Players[1].IsPartner = true

  --Partner Name
local ch = false
local name = ""
while not ch do
    name = ""
	while name == "" do
      UI:NameMenu(STRINGS:Format(STRINGS.MapStrings['Name_Title']), "")
      UI:WaitForChoice()
      name = UI:ChoiceResult()
	end
	
	GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(1), name)
    UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Name_Confirm'], name), true)
    UI:WaitForChoice()
    ch = UI:ChoiceResult()
end

SV.General.Starter = GAME:GetPlayerPartyMember(0)
SV.General.Partner = GAME:GetPlayerPartyMember(1)

GROUND:Unhide("PLAYER")

GAME:MoveCamera(24, 0, 60, true)

local player = GAME:GetPlayerPartyMember(0)
local partner = GAME:GetPlayerPartyMember(1)

local player_name = GAME:GetCharacterNickname(player)
local partner_name = GAME:GetCharacterNickname(partner)

UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Conclusion'], player_name, partner_name))
GAME:WaitFrames(60)

local player_ground = CH('PLAYER')


local coro_camera = TASK:BranchCoroutine(function() GAME:MoveCamera(24, 48, 180, true) end)
local coro_player = TASK:BranchCoroutine(function() GROUND:MoveInDirection(player_ground, Direction.Up, 72, false, 6) end)
local coro_partner = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner_ground, Direction.Up, 72, false, 6) end)
local coro_fade = TASK:BranchCoroutine(function() GAME:FadeOut(true, 120) end)
local coro_fade_bgm = TASK:BranchCoroutine(function() SOUND:FadeOutBGM(120) end)

TASK:JoinCoroutines({coro_camera, coro_player, coro_partner, coro_fade, coro_fade_bgm})

GROUND:SetPlayer(GAME:GetPlayerPartyMember(0))
GAME:SetCanSwitch(false)
GAME:SetTeamName('')
_DATA.Save.ActiveTeam:SetRank('none')
_DATA.Save.ActiveTeam.Fame = 0
_DATA.Save:UpdateTeamProfile(true)


GAME:EnterGroundMap("chapter_card", "Entrance")

end

---start_quiz.Exit(map)
--Engine callback function
function start_quiz.Exit(map)


end

---start_quiz.Update(map)
--Engine callback function
function start_quiz.Update(map)


end

---start_quiz.GameSave(map)
--Engine callback function
function start_quiz.GameSave(map)


end

---start_quiz.GameLoad(map)
--Engine callback function
function start_quiz.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return start_quiz

