--[[
    init.lua
    Created: 08/10/2026 15:15:47
    Description: Autogenerated script file for the map chp1_great_canyon.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local chp1_great_canyon = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chp1_great_canyon.Init(map)
--Engine callback function
function chp1_great_canyon.Init(map)


end

---chp1_great_canyon.Enter(map)
--Engine callback function
function chp1_great_canyon.Enter(map)

  GAME:FadeIn(20)

end

---chp1_great_canyon.Exit(map)
--Engine callback function
function chp1_great_canyon.Exit(map)


end

---chp1_great_canyon.Update(map)
--Engine callback function
function chp1_great_canyon.Update(map)


end

---chp1_great_canyon.GameSave(map)
--Engine callback function
function chp1_great_canyon.GameSave(map)


end

---chp1_great_canyon.GameLoad(map)
--Engine callback function
function chp1_great_canyon.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chp1_great_canyon

