--[[
    init.lua
    Created: 08/12/2026 21:37:03
    Description: Autogenerated script file for the map chp1_wormhole.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local chp1_wormhole = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chp1_wormhole.Init(map)
--Engine callback function
function chp1_wormhole.Init(map)


end

---chp1_wormhole.Enter(map)
--Engine callback function
function chp1_wormhole.Enter(map)
  
  GAME:FadeIn(20)

end

---chp1_wormhole.Exit(map)
--Engine callback function
function chp1_wormhole.Exit(map)


end

---chp1_wormhole.Update(map)
--Engine callback function
function chp1_wormhole.Update(map)


end

---chp1_wormhole.GameSave(map)
--Engine callback function
function chp1_wormhole.GameSave(map)


end

---chp1_wormhole.GameLoad(map)
--Engine callback function
function chp1_wormhole.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chp1_wormhole

