--[[
    init.lua
    Created: 08/10/2026 15:52:16
    Description: Autogenerated script file for the map chp1_ultra.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local chp1_ultra = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chp1_ultra.Init(map)
--Engine callback function
function chp1_ultra.Init(map)


end

---chp1_ultra.Enter(map)
--Engine callback function
function chp1_ultra.Enter(map)
  GROUND:Hide('PLAYER')
  GAME:CutsceneMode(true)
  UI:WaitShowBG("Black", 1, 1)
  local title_credit = {
    STRINGS:Format(STRINGS.MapStrings['Credit_1']),
    STRINGS:Format(STRINGS.MapStrings['Credit_2']),
    STRINGS:Format(STRINGS.MapStrings['Credit_3']),
  }

  SOUND:PlayBGM("INTRODUCTION.ogg", true)
  GAME:FadeIn(60)
  UI:WaitShowTitle(STRINGS:Format(title_credit[1]), 60)
	GAME:WaitFrames(240)
	UI:WaitHideTitle(60)

  local coro1 = TASK:BranchCoroutine(function() 
    GAME:MoveCamera(0, -96, 660, true)
    UI:WaitShowBG("Black", 60, 60)
  end)
  local coro2 = TASK:BranchCoroutine(function() 
    GAME:WaitFrames(60)

    UI:WaitShowTitle(STRINGS:Format(title_credit[2]), 60)
	  GAME:WaitFrames(240)
	  UI:WaitHideTitle(60)

    UI:WaitShowTitle(STRINGS:Format(title_credit[3]), 60)
	  GAME:WaitFrames(300)
	  UI:WaitHideTitle(60)
  end)
  local coro3 = TASK:BranchCoroutine(function() 
    UI:WaitHideBG(120)
  end)

  TASK:JoinCoroutines({coro_1, coro_2, coro_3})
  GAME:WaitFrames(900)

  local player = GAME:GetPlayerPartyMember(0)

  local title_narration = {
    STRINGS:Format(STRINGS.MapStrings['Narration_1']),
    STRINGS:Format(STRINGS.MapStrings['Narration_2'], GAME:GetCharacterNickname(player)),
    STRINGS:Format(STRINGS.MapStrings['Narration_3']),
  }

  UI:WaitShowTitle(title_narration[1], 60)
  GAME:WaitFrames(120)
  UI:WaitHideTitle(120)
	UI:WaitShowTitle(title_narration[2], 60)
  GAME:WaitFrames(120)
  UI:WaitHideTitle(120)
	UI:WaitShowTitle(title_narration[3], 60)
  GAME:WaitFrames(120)
  UI:WaitHideTitle(120)

  SOUND:FadeOutBGM(120)
  GAME:WaitFrames(120)
  GAME:EnterGroundMap("chp1_solgaleo", "Entrance")
end

---chp1_ultra.Exit(map)
--Engine callback function
function chp1_ultra.Exit(map)


end

---chp1_ultra.Update(map)
--Engine callback function
function chp1_ultra.Update(map)


end

---chp1_ultra.GameSave(map)
--Engine callback function
function chp1_ultra.GameSave(map)


end

---chp1_ultra.GameLoad(map)
--Engine callback function
function chp1_ultra.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chp1_ultra

