--[[
    init.lua
    Created: 06/30/2026 17:28:51
    Description: Autogenerated script file for the map island_forest.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local island_forest = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---island_forest.Init(zone)
--Engine callback function
function island_forest.Init(zone)


end

---island_forest.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function island_forest.EnterSegment(zone, rescuing, segmentID, mapID)


end

---island_forest.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function island_forest.ExitSegment(zone, result, rescue, segmentID, mapID)

end

---island_forest.Rescued(zone, name, mail)
--Engine callback function
function island_forest.Rescued(zone, name, mail)


end

return island_forest

