--[[
    init.lua
    Created: 06/28/2026 16:50:31
    Description: Autogenerated script file for the map start_camp.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local start_camp = {}

-------------------------------
-- Map Callbacks
-------------------------------
---start_camp.Init(map)
--Engine callback function
function start_camp.Init(map)


end

---start_camp.Enter(map)
--Engine callback function
function start_camp.Enter(map)

  GAME:FadeIn(20)

end

---start_camp.Exit(map)
--Engine callback function
function start_camp.Exit(map)


end

---start_camp.Update(map)
--Engine callback function
function start_camp.Update(map)


end

---start_camp.GameSave(map)
--Engine callback function
function start_camp.GameSave(map)


end

---start_camp.GameLoad(map)
--Engine callback function
function start_camp.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return start_camp

