--[[
    init.lua
    Created: 07/01/2026 22:13:01
    Description: Autogenerated script file for the map island_woods.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local island_woods = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---island_woods.Init(zone)
--Engine callback function
function island_woods.Init(zone)


end

---island_woods.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function island_woods.EnterSegment(zone, rescuing, segmentID, mapID)


end

---island_woods.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function island_woods.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---island_woods.Rescued(zone, name, mail)
--Engine callback function
function island_woods.Rescued(zone, name, mail)


end

return island_woods

