--[[
    init.lua
    Created: 06/28/2026 19:30:57
    Description: Autogenerated script file for the map island_camp.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local island_camp = {}

-------------------------------
-- Map Callbacks
-------------------------------
---island_camp.Init(map)
--Engine callback function
function island_camp.Init(map)
  if SV.island_camp == nil then
    SV.island_camp = {}
  end

  if SV.island_camp.WatchedCutscene == nil then
    SV.island_camp.WatchedCutscene = 0
  end

  if SV.island_camp.TalkedToRiolu == nil then
    SV.island_camp.TalkedToRiolu = 0
  end

  if SV.island_camp.TalkedToEevee == nil then
    SV.island_camp.TalkedToEevee = 0
  end

  if SV.island_camp.DataInitialized == nil then
    local charmander = _DATA.Save.ActiveTeam.Players[0]
    local riolu = _DATA.Save.ActiveTeam:CreatePlayer(
      _DATA.Save.Rand,
      RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Male),
      50,
      "",
      -1
    )
    local eevee = _DATA.Save.ActiveTeam:CreatePlayer(
      _DATA.Save.Rand,
      RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Male),
      50,
      "",
      -1
    )

    _DATA.Save.ActiveTeam.Players:Add(riolu)
    _DATA.Save.ActiveTeam.Players:Add(eevee)

    GAME:SetCharacterSkill(charmander, "slash", 0, true)
    GAME:SetCharacterSkill(charmander, "flamethrower", 1, true)
    GAME:SetCharacterSkill(charmander, "dragon_breath", 2, true)
    GAME:SetCharacterSkill(charmander, "inferno", 3, true)

    GAME:SetCharacterSkill(riolu, "force_palm", 0, true)
    GAME:SetCharacterSkill(riolu, "vacuum_wave", 1, true)
    GAME:SetCharacterSkill(riolu, "metal_claw", 2, true)
    GAME:SetCharacterSkill(riolu, "bulk_up", 3, true)

    GAME:SetCharacterSkill(eevee, "swift", 0, true)
    GAME:SetCharacterSkill(eevee, "bite", 1, true)
    GAME:SetCharacterSkill(eevee, "refresh", 2, true)
    GAME:SetCharacterSkill(eevee, "helping_hand", 3, true)

    SV.island_camp.DataInitialized = 1
  end

end

---island_camp.Enter(map)
--Engine callback function
function island_camp.Enter(map)
  local player = CH('PLAYER')
  local charmander = CH('cutscene_charmander')
  local riolu = CH('cutscene_riolu')
  local eevee = CH('cutscene_eevee')
  local kingambit = CH('kingambit')
  local druddigon = CH('druddigon')

  if SV.island_camp.WatchedCutscene == 0 then
    GAME:CutsceneMode(true)

    GROUND:Hide('PLAYER')
  
    UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 30)
    GAME:WaitFrames(60)
    UI:WaitHideTitle(40)

    GAME:MoveCamera(252, 384, 1, false)

    GROUND:Unhide('cutscene_charmander')
    GROUND:Unhide('cutscene_riolu')
    GROUND:Unhide('cutscene_eevee')

    local coro_fade = TASK:BranchCoroutine(function() GAME:FadeIn(40) end)
    local coro_camera = TASK:BranchCoroutine(function() GAME:MoveCamera(252, 192, 240, false) end)
    local coro_walk_0 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(charmander, Direction.Up, 160, false, 1) end)
    local coro_walk_1 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(riolu, Direction.Up, 160, false, 1) end)
    local coro_walk_2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(eevee, Direction.Up, 160, false, 1) end)

    TASK:JoinCoroutines({coro_fade, coro_camera, coro_walk_0, coro_walk_1, coro_walk_2})

    GROUND:CharSetAnim(charmander, "None", false)
    GROUND:CharSetAnim(eevee, "None", false)
    GROUND:CharSetAnim(riolu, "None", false)
  
    GAME:WaitFrames(60)

    UI:SetSpeaker(charmander)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_0'], kingambit:GetDisplayName()))
    UI:SetSpeaker(eevee)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_0']))
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_0']))
    UI:SetSpeaker(charmander)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_1']))
    UI:SetSpeaker(eevee)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_1'], kingambit:GetDisplayName()))
    UI:SetSpeaker(riolu)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_1']))
    UI:SetSpeaker(charmander)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_2']))
    UI:SetSpeaker(eevee)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_2']))
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_2']))
    UI:SetSpeaker(eevee)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_3'], charmander:GetDisplayName()))
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_3']))
    UI:SetSpeaker(eevee)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_4']))
    UI:SetSpeaker(charmander)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_3']))
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_4']))
    UI:SetSpeaker(charmander)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_4'], druddigon:GetDisplayName()))
    GROUND:CharSetEmote(riolu, "shock", 1)
    SOUND:PlayBattleSE("EVT_Emote_Shock_Bad")
    GAME:WaitFrames(30)
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Surprised")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_5']))
    UI:SetSpeaker(eevee)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_eevee_5']))
    GROUND:CharSetEmote(riolu, "sweating", 1)
    SOUND:PlayBattleSE("EVT_Emote_Sweating")
    GAME:WaitFrames(30)
    UI:SetSpeaker(riolu)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_riolu_6']))
    UI:SetSpeaker(charmander)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['cutscene_charmander_5']))
  
    GAME:WaitFrames(60)
    GAME:FadeOut(false, 60)
    GROUND:Unhide("PLAYER")
    GROUND:Hide('cutscene_charmander')
    GROUND:Hide('cutscene_riolu')
    GROUND:Hide('cutscene_eevee')

    GROUND:Unhide("riolu")
    GROUND:Unhide("eevee")
    GAME:MoveCamera(0, 0, 0, true)
    GAME:FadeIn(60)
    GAME:WaitFrames(30)


    GAME:CutsceneMode(false)
    SV.island_camp.WatchedCutscene = 1
  end

  
end

---island_camp.Exit(map)
--Engine callback function
function island_camp.Exit(map)


end

---island_camp.Update(map)
--Engine callback function
function island_camp.Update(map)


end

---island_camp.GameSave(map)
--Engine callback function
function island_camp.GameSave(map)


end

---island_camp.GameLoad(map)
--Engine callback function
function island_camp.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function island_camp.riolu_Action(obj, activator)

  if SV.island_camp.TalkedToRiolu == 0 then

    GROUND:CharTurnToChar(obj,CH('PLAYER'))
    local eevee = CH('eevee')
    local druddigon = CH('druddigon')

    UI:SetSpeaker(obj)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_r0'], activator:GetDisplayName()))
    UI:ResetSpeaker()
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_pause']))
    GAME:WaitFrames(30)
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_c0']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_r1'], eevee:GetDisplayName()))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_c1']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_r2']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_c2']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_r3']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_c3'], druddigon:GetDisplayName()))

    UI:SetSpeakerEmotion("Normal")

    GROUND:EntTurn(obj, Direction.DownRight)

    SV.island_camp.TalkedToRiolu = 1
  else 
    local kingambit = CH('kingambit')
    GROUND:CharTurnToChar(obj,CH('PLAYER'))
    UI:SetSpeaker(obj)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_riolu_default'], kingambit:GetDisplayName()))
    GROUND:EntTurn(obj, Direction.DownRight)
  end

end

function island_camp.eevee_Action(obj, activator)
  if SV.island_camp.TalkedToEevee == 0 then

    local eevee = CH('eevee')
    GROUND:CharTurnToChar(obj,CH('PLAYER'))

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c0'], eevee:GetDisplayName()))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_e0']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c1']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_e1']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c2']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_e2']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c3']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_e3']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c4']))
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_e4']))
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_c5']))

    UI:SetSpeakerEmotion("Normal")

    GROUND:EntTurn(obj, Direction.DownLeft)

    SV.island_camp.TalkedToEevee = 1
  else 
    GROUND:CharTurnToChar(obj,CH('PLAYER'))
    UI:SetSpeaker(obj)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['npc_eevee_default'], activator:GetDisplayName()))
    GROUND:EntTurn(obj, Direction.DownLeft)
  end

end

return island_camp

